-- Add Shields (22 shields for levels 1-60)
INSERT INTO items (name, description, type, slot, rarity, armor, constitution_bonus, strength_bonus, required_level, value, stackable) VALUES
('Wooden Buckler', 'A sturdy shield that provides protection and enhances defensive capabilities.', 'armor', 'offhand', 'common', 2, 1, 0, 1, 15, 0),
('Iron Buckler', 'A sturdy shield that provides protection and enhances defensive capabilities.', 'armor', 'offhand', 'common', 3, 1, 0, 3, 45, 0),
('Steel Shield', 'A sturdy shield that provides protection and enhances defensive capabilities.', 'armor', 'offhand', 'uncommon', 4, 2, 1, 5, 75, 0),
('Reinforced Shield', 'A sturdy shield that provides protection and enhances defensive capabilities.', 'armor', 'offhand', 'uncommon', 5, 2, 1, 8, 120, 0),
('Tower Shield', 'A sturdy shield that provides protection and enhances defensive capabilities.', 'armor', 'offhand', 'uncommon', 6, 3, 2, 10, 150, 0),
('Guardian Shield', 'A sturdy shield that provides protection and enhances defensive capabilities.', 'armor', 'offhand', 'rare', 7, 3, 2, 12, 270, 0),
('Tempered Kite Shield', 'A sturdy shield that provides protection and enhances defensive capabilities.', 'armor', 'offhand', 'rare', 8, 4, 2, 15, 338, 0),
('Bulwark of the Mountain', 'A sturdy shield that provides protection and enhances defensive capabilities.', 'armor', 'offhand', 'rare', 9, 5, 3, 18, 405, 0),
('Mithril Shield', 'A sturdy shield that provides protection and enhances defensive capabilities.', 'armor', 'offhand', 'rare', 10, 6, 3, 21, 473, 0),
('Enchanted Tower Shield', 'A sturdy shield that provides protection and enhances defensive capabilities.', 'armor', 'offhand', 'rare', 11, 7, 4, 24, 540, 0),
('Runic Greatshield', 'A sturdy shield that provides protection and enhances defensive capabilities.', 'armor', 'offhand', 'rare', 12, 8, 4, 27, 608, 0),
('Dragonscale Barrier', 'A sturdy shield that provides protection and enhances defensive capabilities.', 'armor', 'offhand', 'epic', 13, 9, 5, 30, 900, 0),
('Obsidian Bulwark', 'A sturdy shield that provides protection and enhances defensive capabilities.', 'armor', 'offhand', 'epic', 14, 10, 5, 33, 990, 0),
('Starforged Aegis', 'A sturdy shield that provides protection and enhances defensive capabilities.', 'armor', 'offhand', 'epic', 15, 11, 6, 36, 1080, 0),
('Voidplate Shield', 'A sturdy shield that provides protection and enhances defensive capabilities.', 'armor', 'offhand', 'epic', 16, 12, 6, 39, 1170, 0),
('Celestial Ward', 'A sturdy shield that provides protection and enhances defensive capabilities.', 'armor', 'offhand', 'epic', 17, 13, 7, 42, 1260, 0),
('Ethereal Bastion', 'A sturdy shield that provides protection and enhances defensive capabilities.', 'armor', 'offhand', 'epic', 18, 14, 7, 45, 1350, 0),
('Primordial Wall', 'A sturdy shield that provides protection and enhances defensive capabilities.', 'armor', 'offhand', 'epic', 19, 15, 8, 48, 1440, 0),
('Godforged Rampart', 'A sturdy shield that provides protection and enhances defensive capabilities.', 'armor', 'offhand', 'legendary', 20, 16, 9, 51, 2295, 0),
('Timeless Bulwark', 'A sturdy shield that provides protection and enhances defensive capabilities.', 'armor', 'offhand', 'legendary', 21, 17, 9, 54, 2430, 0),
('Shield of the Immortal', 'A sturdy shield that provides protection and enhances defensive capabilities.', 'armor', 'offhand', 'legendary', 22, 18, 10, 57, 2565, 0),
('Ascendant Aegis', 'A sturdy shield that provides protection and enhances defensive capabilities.', 'armor', 'offhand', 'legendary', 24, 20, 12, 60, 2700, 0);
